[features]
seeds = true

[provider]
cluster = "localnet"
wallet = "~/.config/solana/devnet.json"

[programs.localnet]
membrz = "GMpDFEBcv4M6hhNrKq9FcVF5NGtvvedjKZKG38T7opdH"

[workspace]
members = ["programs/membrz"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
